kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-goofys
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-goofys
  storageClassName: ""
