apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blobfuse
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: blobfuse.csi.azure.com
