---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: goofys.csi.azure.com
provisioner: goofys.csi.azure.com
parameters:
  skuName: Premium_LRS  # available values: Premium_LRS, Premium_GRS, Premium_RAGRS
  containerName: test  # if container "test" does not exist, driver will create "test" container
reclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
volumeBindingMode: Immediate
mountOptions:
  - -o allow_other
  - --file-mode=0777
  - --dir-mode=0777
